global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
